# Generated by Django 5.1.4 on 2025-01-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrudData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='')),
                ('Age', models.CharField(max_length=50, verbose_name='')),
                ('Email', models.EmailField(max_length=254, verbose_name='')),
                ('Degree', models.CharField(max_length=50, verbose_name='')),
                ('Passed_out', models.CharField(max_length=50, verbose_name='')),
            ],
        ),
    ]
