# Generated by Django 5.1.4 on 2025-01-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruddata',
            name='Age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cruddata',
            name='Passed_out',
            field=models.IntegerField(),
        ),
    ]
